CREATE DATABASE CLINICA_DB;
GO

USE CLINICA_DB;
GO

--DROP DATABASE CLINICA_DB;


CREATE TABLE [dbo].[PACIENTES] (
    [IdPaciente] INT IDENTITY(1,1) NOT NULL,
    [TipoDocumento] VARCHAR(20) NOT NULL,   -- DNI / PASAPORTE / OTRO
    [DniPaciente] INT NOT NULL,
    [Nombres] VARCHAR(50) NOT NULL,
    [Apellidos] VARCHAR(50) NOT NULL,
    [FechaNacimiento] DATE NOT NULL,
    [Sexo] CHAR(1) NOT NULL,                -- F / M / O
    [Email] VARCHAR(100) NOT NULL,
    [Telefono] VARCHAR(20) NULL,
    [Celular] VARCHAR(20) NULL,
    [Direccion] VARCHAR(100) NOT NULL,
    [Ciudad] VARCHAR(100) NOT NULL,
    [Provincia] VARCHAR(100) NOT NULL,
    [CodigoPostal] VARCHAR(10) NOT NULL,
    [ObraSocial] VARCHAR(40) NULL,
    [NumeroObraSocial] VARCHAR(40) NULL,

    CONSTRAINT PK_PACIENTES PRIMARY KEY (IdPaciente),
    CONSTRAINT UQ_PACIENTES_DNI UNIQUE (DniPaciente),
    CONSTRAINT CK_PACIENTES_SEXO CHECK (Sexo IN ('F', 'M', 'O')),
    CONSTRAINT CK_PACIENTES_TIPODOC CHECK (TipoDocumento IN ('DNI', 'PASAPORTE', 'OTRO'))
);


GO


CREATE TABLE [dbo].[ESPECIALIDAD](
    [IdEspecialidad] INT IDENTITY(1,1) NOT NULL,
    [Nombre] VARCHAR(50) NOT NULL,
    [Descripcion] VARCHAR(200) NOT NULL,

    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (IdEspecialidad ASC)
);
GO

CREATE TABLE [dbo].[TURNO_TRABAJO] (
    IdTurnoTrabajo INT IDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    HoraEntrada TIME NOT NULL,
    HoraSalida TIME NOT NULL,

	CONSTRAINT PK_TURNO_TRABAJO PRIMARY KEY (IdTurnoTrabajo));
GO


CREATE TABLE [dbo].[MEDICO](
    [IdMedico] INT IDENTITY(1,1) NOT NULL,
    [Nombre] VARCHAR(50) NOT NULL,
    [Apellido] VARCHAR(50) NOT NULL,
    [Dni] VARCHAR(20) NOT NULL,
    [Telefono] VARCHAR(20),
    [Email] VARCHAR(100),
    [IdTurnoTrabajo] INT NULL,

    CONSTRAINT PK_MEDICO PRIMARY KEY (IdMedico),
    CONSTRAINT FK_MEDICO_TURNO_TRABAJO FOREIGN KEY (IdTurnoTrabajo)
        REFERENCES TURNO_TRABAJO(IdTurnoTrabajo)
);
GO

CREATE TABLE [dbo].[MEDICO_ESPECIALIDAD] (
    IdMedico INT NOT NULL,
    IdEspecialidad INT NOT NULL,

    CONSTRAINT PK_MEDICO_ESPECIALIDAD PRIMARY KEY (IdMedico, IdEspecialidad),
    CONSTRAINT FK_ME_MEDICO FOREIGN KEY (IdMedico) REFERENCES MEDICO(IdMedico),
    CONSTRAINT FK_ME_ESPECIALIDAD FOREIGN KEY (IdEspecialidad) REFERENCES ESPECIALIDAD(IdEspecialidad));
GO

CREATE TABLE [dbo].[TURNO](
    IdTurno INT IDENTITY(1,1) NOT NULL,
    IdPaciente INT NOT NULL,
    IdMedico INT NOT NULL,
    IdEspecialidad INT NOT NULL,
    Fecha DATETIME NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    Observaciones VARCHAR(500) NULL,

    CONSTRAINT PK_TURNO PRIMARY KEY (IdTurno),
    CONSTRAINT FK_TURNO_PACIENTE FOREIGN KEY (IdPaciente) REFERENCES PACIENTES(IdPaciente),
    CONSTRAINT FK_TURNO_MEDICO FOREIGN KEY (IdMedico) REFERENCES MEDICO(IdMedico),
    CONSTRAINT FK_TURNO_ESPECIALIDAD FOREIGN KEY (IdEspecialidad) REFERENCES ESPECIALIDAD(IdEspecialidad)
);
GO

CREATE TABLE [dbo].[NOTIFICACION] (
    IdNotificacion INT IDENTITY(1,1) NOT NULL,
    IdTurno INT NOT NULL,
    FechaEnvio DATETIME NOT NULL,
    Medio VARCHAR(50) NOT NULL,
    Estado VARCHAR(20) NOT NULL,

    CONSTRAINT PK_NOTIFICACION PRIMARY KEY (IdNotificacion),
    CONSTRAINT FK_NOTIF_TURNO FOREIGN KEY (IdTurno) REFERENCES TURNO(IdTurno)
);
GO

CREATE TABLE [dbo].[USUARIO](
    IdUsuario INT IDENTITY(1,1) NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Contraseña VARCHAR(200) NOT NULL,
    Rol VARCHAR(20) NOT NULL,
    Email VARCHAR(100) NOT NULL,

    CONSTRAINT PK_USUARIO PRIMARY KEY (IdUsuario)
);
GO

------------
-- INSERT --

